### PR TITLE
fix event room finding logic used to determine event room url

### LINKED ISSUE #1622: Clicking "Happening now" button on Schedule / event dialog crashes
When I click on an event and then click "Happening now in ..." button, 

image

it crashes with this error message.

```
build.umd.js:645 Uncaught DOMException: Failed to set the 'href' property on 'Location': '//' is not a valid URL.
    at openUrl (https://ohbm.sparkle.space/static/js/main.c4b94700.chunk.js:1:78214)
    at openRoomUrl (https://ohbm.sparkle.space/static/js/main.c4b94700.chunk.js:1:123297)
    at enterExternalRoom (https://ohbm.sparkle.space/static/js/main.c4b94700.chunk.js:1:123365)
    at https://ohbm.sparkle.space/static/js/main.c4b94700.chunk.js:1:126408
    at goToEventLocation (https://ohbm.sparkle.space/static/js/main.c4b94700.chunk.js:1:127655)
    at Object.ba (https://ohbm.sparkle.space/static/js/2.15386b81.chunk.js:2:2022140)
    at ia (https://ohbm.sparkle.space/static/js/2.15386b81.chunk.js:2:2022317)
    at ja (https://ohbm.sparkle.space/static/js/2.15386b81.chunk.js:2:2022489)
    at na (https://ohbm.sparkle.space/static/js/2.15386b81.chunk.js:2:2022585)
    at kc (https://ohbm.sparkle.space/static/js/2.15386b81.chunk.js:2:2039295)
wrapped @ build.umd.js:645
```

### PR DESCRIPTION
**Pull request by alexey-petrov**
Fixed event modal link url
* changed event room find logic

Since event room name could easily not be equal to the actual room title there were cases when we couldn't find a room with the event in question. Now whether user assigns `http://domain/{v || in}/roomName` or simply `roomName` as the event room we'll be able to determine the room to redirect him into

Fixes #1622
fixes #1585 

image
image

### CODE REVIEW

File: src/components/organisms/EventModal/EventModal.tsx [hunk 1]
```diff
@@ -37,7 +37,15 @@ export const EventModal: React.FC<EventModalProps> = ({
...
+      eventVenue?.rooms?.find((room) => {
+        const noSlashUrl = room.url.endsWith("/")
+          ? room.url.slice(0, -1)
+          : room.url;
+        const [roomName] = noSlashUrl.split("/").slice(-1);
+
+        return event?.room?.endsWith(`${roomName}`);
+      }),
     [eventVenue, event]
   );
```
Comment (0xdevalias) [inline src/components/organisms/EventModal/EventModal.tsx:50]: The changes here probably should be wrapped up into a helper method somewhere in `utils/*`.

Also, are there more locations across the platform that have similar logic to this/would have the same sort of bug/issues? I believe there will be, so we should be ensuring we fix it correctly in all locations.

**Review by 0xdevalias — CHANGES_REQUESTED** [review]
Questions/comments/changes.

---

> Since event room name could easily not be equal to the actual room title there were cases when we couldn't find a room with the event in question. Now whether user assigns `http://domain/{v || in}/roomName` or simply `roomName` as the event room we'll be able to determine the room to redirect him into

@alexey-petrov The comments you made here seem to imply that you think that 'room name' equates to the `venueId` part of `/v/:venueId`, `/in/:venueId`, etc; but that's not the case.

'Room name' is an entirely seperate concept to `venueId`. 'Rooms'/'portals' only really exist within a map, and only contain the details used to display the icon on the map, and to link to the underlying _venue_. Venue's are referenced by their `venueId`.

So with that updated context, are the changes you're making here correct still?

**Comment by 0xdevalias** [comment]
> Since event room name could easily not be equal to the actual room title there were cases when we couldn't find a room with the event in question. Now whether user assigns `http://domain/{v || in}/roomName` or simply `roomName` as the event room we'll be able to determine the room to redirect him into

@alexey-petrov The comments you made here seem to imply that you think that 'room name' equates to the `venueId` part of `/v/:venueId`, `/in/:venueId`, etc; but that's not the case.

'Room name' is an entirely seperate concept to `venueId`. 'Rooms'/'portals' only really exist within a map, and only contain the details used to display the icon on the map, and to link to the underlying _venue_. Venue's are referenced by their `venueId`.

So with that updated context, are the changes you're making here correct still?

File: src/components/organisms/EventModal/EventModal.tsx (hunk 1 above)
Comment (0xdevalias) [reply src/components/organisms/EventModal/EventModal.tsx:50]: Also, 'rooms'/'portals' can link to external URLs.. will that impact your logic here?

Comment (0xdevalias) [reply src/components/organisms/EventModal/EventModal.tsx:50]: We may also want to make use of `matchPath` from https://reactrouter.com/web/api/matchPath wrather than attempting to 'roll our own' with regards to extracting sub-sections of in-platform URLs, since this is the same logic/lib that our actual routing uses.

In doing so, we would want to extract the relevant paths into a `const` in `src/settings` or similar, and use that in both `AppRouter` and the `utils/*` function that ends up using `matchPath` for this logic.

Comment (0xdevalias) [reply src/components/organisms/EventModal/EventModal.tsx:50]: There are also a bunch of helpers/etc in `src/utils/url.ts` that may be relevant here.

**Comment by alexey-petrov** [comment]
> Questions/comments/changes.
> 
> > Since event room name could easily not be equal to the actual room title there were cases when we couldn't find a room with the event in question. Now whether user assigns `http://domain/{v || in}/roomName` or simply `roomName` as the event room we'll be able to determine the room to redirect him into
> 
> @alexey-petrov The comments you made here seem to imply that you think that 'room name' equates to the `venueId` part of `/v/:venueId`, `/in/:venueId`, etc; but that's not the case.
> 
> 'Room name' is an entirely seperate concept to `venueId`. 'Rooms'/'portals' only really exist within a map, and only contain the details used to display the icon on the map, and to link to the underlying _venue_. Venue's are referenced by their `venueId`.
> 
> So with that updated context, are the changes you're making here correct still?

thanks for the explanation, now the whole difference between room/venue is way more clear
And yes, the changes should still be correct

File: src/components/organisms/EventModal/EventModal.tsx (hunk 1 above)
Comment (alexey-petrov) [reply src/components/organisms/EventModal/EventModal.tsx]: I've moved this logic into helpers in /src/utils/url.ts at 8b0a07c
I've been thinking about the matchPath and overall url approach and that got me to a conclusion that it might not work as we want here
since both room/event urls can be set without any url validation ( really any string that you can imagine ), the matchpath here won't be working properly when checking those urls, so that made me think that we should add some sort of validation to the room/event url field ( probably not in this task tho? ) 
also, I've added specific if clause for the external URL ( thank you ) , so now even if user adds an external URL to an event and eventRoom is not found, he will still be able to visit that url by clicking on the redirect btn

**Review by yurii-lubynets — APPROVED** [review]

**Comment by alexey-petrov** [comment]
> Questions/comments/changes.
> 
> > Since event room name could easily not be equal to the actual room title there were cases when we couldn't find a room with the event in question. Now whether user assigns `http://domain/{v || in}/roomName` or simply `roomName` as the event room we'll be able to determine the room to redirect him into
> 
> @alexey-petrov The comments you made here seem to imply that you think that 'room name' equates to the `venueId` part of `/v/:venueId`, `/in/:venueId`, etc; but that's not the case.
> 
> 'Room name' is an entirely seperate concept to `venueId`. 'Rooms'/'portals' only really exist within a map, and only contain the details used to display the icon on the map, and to link to the underlying _venue_. Venue's are referenced by their `venueId`.
> 
> So with that updated context, are the changes you're making here correct still?

https://github.com/sparkletown/sparkle/pull/1696#discussion_r661384125

File: src/components/organisms/EventModal/EventModal.tsx (hunk 1 above)
Comment (0xdevalias) [reply src/components/organisms/EventModal/EventModal.tsx]: > so that made me think that we should add some sort of validation to the room/event url field ( probably not in this task tho? )

I think we might already have a backlog issue for this, but if not, it would be good to create one.

**Comment by 0xdevalias** [comment]
@alexey-petrov This PR should NOT have been merged, as you had made multiple commits to it since the time it was reviewed.. Please do NOT do this again. Request a re-review and wait for it like everyone else.

image

(cc // @jonboutelle FYI)

**Comment by alexey-petrov** [comment]
> @alexey-petrov This PR should NOT have been merged, as you had made multiple commits to it since the time it was reviewed.. Please do NOT do this again. Request a re-review and wait for it like everyone else.
> 
> image
> 
> (cc // @jonboutelle FYI)

my bad, my thought was that the changes weren't that big, which basically introduced some code formatting and like one extra function to work with a string in one exact case
but I won't do it again

**Comment by 0xdevalias** [comment]
> my bad, my thought was that the changes weren't that big, which basically introduced some code formatting and like one extra function to work with a string in one exact case
> but I won't do it again

@alexey-petrov Thanks :) I guess I mostly saw the number of commits and assumed, didn't look at the code diff.
